"""empty message

Revision ID: 859c7fd51c6e
Revises: ae87cac34300
Create Date: 2020-06-19 17:56:30.625869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859c7fd51c6e'
down_revision = 'ae87cac34300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('five_min_reminded', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('one_hour_reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'one_hour_reminded')
    op.drop_column('event', 'five_min_reminded')
    # ### end Alembic commands ###
