"""empty message

Revision ID: ae87cac34300
Revises: c58201f0e761
Create Date: 2020-06-19 12:19:08.840034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae87cac34300'
down_revision = 'c58201f0e761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_creation_time', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('users', 'name')
    op.drop_column('event', 'event_creation_time')
    # ### end Alembic commands ###
